# Generated by Django 4.2.9 on 2024-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("file_link", models.CharField(max_length=255)),
            ],
        ),
    ]
